### ISSUE TITLE
Measurement failed for inversion recovery GRE sequence 

### ISSUE THREAD

**Issue by qianenlin** [pulseq/pulseq#3]
Hi,

I am trying to construct sequence with a 180 degree pulse followed by 30 degree pulses. When I try to execute the sequence on the scanner, an error message "start of measurement failed" popped up. I am wondering what the problem is and could you help with it? Thanks!

**Comment by stefan-k** [comment]
Hi,

Could you please show us a minimal example?

Thanks!

**Comment by qianenlin** [comment]
Sorry for keeping this issue posted for this long. The problem is resolved now. Thank you!
