### ISSUE TITLE
Specification Inconsistency When Parsing RF Dwell Time in ExternalSequence.cpp

### ISSUE THREAD

**Issue by zhengliuer** [pulseq/pulseq#54]
Hello, I want to talk about something may need to be fixed about parsing RF dwell time in ExternalSequence.cpp:
https://github.com/pulseq/pulseq/blob/master/src/ExternalSequence.cpp#L1075-L1124

```C++
float fDwellTime_us=0;
// feature of v1.4.x
// handle time shape 
if (block->rf.timeShape) 
{
	// new file format (v1.4.x)
	CompressedShape& shapeTime = m_shapeLibrary[block->rf.timeShape];
	// detect regular sampling 
	if (shapeTime.samples.size()!=shapeTime.numUncompressedSamples &&
		(shapeTime.samples.size()==3 || shapeTime.samples.size()==4)) 
	{
		// size=3: 1 1 N-2; size=4: t0 d d N-3 
		// in both cases the actuall dwell time is stored at shapeTime.samples[1]
		fDwellTime_us=m_dRadiofrequencyRasterTime_us*shapeTime.samples[1]; // no need to unpack 
	}
	else
	{
		std::vector<float> waveform_t;
		waveform_t.resize(shapeTime.numUncompressedSamples);
		if (!decompressShape(shapeTime,&waveform_t[0]))
			return false;
		// we resample the input on the fly 
		// for now we just use the RF raster time
		fDwellTime_us=m_dRadiofrequencyRasterTime_us;
		int nSamples=int(0.5+waveform_t.back());
		// for now we use nearest neighbour/right repetition interpolation
		// FIXME/TODO: convert to complex, use linear interpolation and convert back to magnitude&phase
		std::vector<float> wv_a(nSamples);
		std::vector<float> wv_p(nSamples);
		int tc=0;
		for(int c=0;c<nSamples;++c)
		{
			if(waveform_t[tc]<(c+1)) 
			{
				if (tc<waveform_t.size())
					++tc;
			}
			wv_a[c]=waveform[tc];
			wv_p[c]=waveform_p[tc];
		}
		// replace the waveforms
		waveform.swap(wv_a);
		waveform_p.swap(wv_p);
	}
}
else
{
	// compatibility mode with the older pulseq versions
	fDwellTime_us=1.0; // old Pulseq's predefined RF raster time
}
```

Code here checks if rf.time_shape_id is not 0, if not 0, calculate the rf dwell time, if is 0, then use old Pulseq's predefined RF raster time, as in 1us. However, in the specification, it says if time shape id is 0, then it means this rf event uses rf raster time as its dwell time, which is defined in mr.opts. So if users defined rf raster time as 0.1us, and the time shape id of rf is 0(uses rf raster time), when using C++ to get rf dwell time, we will have 1us, not 0.1us(rf raster time), which is an error.

Also, in `rfFromLibData`, the function in mr.Sequence, it uses rf raster time directly to calculate rf.shape_dur if time shape id d is 0, which is as expected.

Best regards,
Zheng Liu

**Comment by m-a-x-i-m-z** [comment]
Hi Zheng Liu,

Good point, thanks for spotting out. Please check the fix in the current 'dev' branch.

Best, 
Maxim

**Comment by zhengliuer** [comment]
Thanks a lot!

Best regards,
Zheng Liu
