### ISSUE TITLE
External Triggering Implementation

### ISSUE THREAD

**Issue by eugene17uf** [pulseq/pulseq#7]
Hello

I am just starting to look at Pulseq implementation, which looks like a great tool for sequence developers. I was wondering if there is an example implementation of external triggering, such as optical triggering in Siemens scanners. Let me know at your earliest convenience.

Thank You
Eugene Milshteyn

**Comment by stefan-k** [comment]
So far there is no support for external triggers, but it will be implemented in the near future.

**Comment by m-a-x-i-m-z** [comment]
is supported now starting from version 1.3.0
